CXX = g++ 
# CXX = clang++

BINARIES=submissionTest

# These two lines needed for Gradescope Testing

CXXFLAGS = -Wall -Wno-uninitialized -std=c++11 -I/usr/include/jsoncpp
LDFLAGS = -ljsoncpp

all: ${BINARIES}

tests: ${BINARIES}
	./submissionTest

tddFuncs.o: tddFuncsJSON.cpp	 
	$(CXX) -c $(CXXFLAGS)  $^ -o $@ $(LDFLAGS)

submissionTest: submission.o submissionTest.o tddFuncs.o
	$(CXX) $(CXXFLAGS)  $^ -o $@ $(LDFLAGS)

clean:
	/bin/rm -f ${BINARIES} *.o

